### ISSUE TITLE
Examples of implementation

### ISSUE THREAD

**Issue by davecranwell** [arnaudbreton/angular-youtube#1]
Could someone please provide an example of how you're expected to implement this? 

I'm very new to Angular and I'm having trouble working out how you'd pass it either the ID of the video to play (quite a fundamental problem i'm sure you're agree) or how you'd go about listening for events on the player itself.

Even a quick snippet would be better than none.

**Comment by arnaudbreton** [comment]
Hi,

Sorry about that. I wrote this plugin for a my project but moved to PopcornJS from Mozilla (http://popcornjs.org) since.

I will update the documentation but while waiting here is a snippet to use this module:

The HTML element:

``` html
<div id="ytplayer" youtube-player></div>
```

Next, somewhere, in a controller or another service, set the video ID to play and call the loadPlayer method

``` javascript
angular.module('myApp', ['youtube'])
.controller('TestCtrl', function (youtubePlayerApi) 
{
   youtubePlayerApi.videoId = 'Y6ti5f-LHp4';
   youtubePlayerApi.loadPlayer();
}); 
```

Let me know if it works for you!

Cheers,
Arnaud.

**Comment by jkarmel** [comment]
Heyo, 

So this didn't actually work for me. I used this exact example. 

I know the api is loading and it seems like its even binding to the correct element because I get the following console messages: 

```
Binding to player ytplayer
Youtube API is ready 
```

Any advice?

**Comment by jkarmel** [comment]
My own comment answers the question, the Youtube Api hadn't loaded yet!
